### ISSUE TITLE
Yawp Court

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#651] opened 2023-02-05 09:22 UTC
- **text:** Ruling 5 or new ruling: Rötschreck against the acting minion makes it so the minion using Yawp Court takes two damage, the opponent is sent to torpor afterwards because of Rötschreck, hence no referendum is conducted.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/hZF1Joxwc2s/m/o1FSURsGv0wJ

**Comment by lionel-panhaleux** [comment] 2023-08-16 15:42
Duplicate of #636

**Closed by lionel-panhaleux** 2023-08-16 15:42 UTC
