### ISSUE TITLE
Perfect Clarity

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#707] opened 2023-06-24 18:33 UTC
- **text:** Cards that affect the action that the vampire is performing affects the vampire e.g. Deflection cannot be played
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/VTHXJOrxlP4/m/be0uDkX78NwJ

**Comment by lionel-panhaleux** [comment] 2023-08-18 17:25
Duplicate of #706

**Closed by lionel-panhaleux** 2023-08-18 17:25 UTC
